steps:
  - name: gcr.io/cloud-builders/npm
    args: ['install']
    dir: 'express/server'
    id: 'install packages'

  - name: gcr.io/cloud-builders/npm
    args: ['run', 'test']
    dir: 'express/server'
    id: 'unit tests'

  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', '--project', '$PROJECT_ID',
           '-q', '$_GAE_PROMOTE',
           './server/app.flexible.yaml', '-v', '$_VID']
    id: 'deploy app engine'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'services', '--project', '$PROJECT_ID',
           'set-traffic', '--splits', '$_GAE_TRAFFIC']

timeout: 660s