steps:
  - name: gcr.io/cloud-builders/npm
    args: ['install']
    dir: 'server'
    id: 'install packages'

  - name: gcr.io/cloud-builders/npm
    args: ['run', 'test']
    dir: 'server'
    id: 'unit tests'

  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', './server/app.flexible.yaml', '-v', '$_VID']
    id: 'deploy app engine'

timeout: 660s