steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=cloudbuild-env
      - --key=firebase-token
    id: 'decrypt'

  - name: gcr.io/$PROJECT_ID/firebase
    args: [ 'use', '$_PROJECT_NAME']
    id: 'use firebase project'

  - name: gcr.io/cloud-builders/npm
    args: ['install']
    id: 'npm install'

#    - name: gcr.io/cloud-builders/npm
#      args: ['run', 'test']
#      id: 'unit tests'

  - name: gcr.io/cloud-builders/npm
    args: ['run', 'build']
    id: 'npm run build'

#  - name: gcr.io/$PROJECT_ID/firebase
#    args: ['deploy', '--only', 'hosting:staging']
#    id: 'deploy to staging env'

  - name: gcr.io/$PROJECT_ID/firebase
    args: ['deploy', '--only', 'hosting:prod']
    id: 'deploy to prod env'
