steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./env.json.enc
      - --plaintext-file=./env.json
      - --location=global
      - --keyring=cloudbuild-env
      - --key=cloudbuild-env
    id: 'decrypt key'

  - name: python:3.7
    args: ['bash', './tweets/tests/runner.sh']
    id: 'pytest unit tests'

  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', './tweets/app.flexible.yaml', '-v', '$SHORT_SHA']
    id: 'deploy app engine'

timeout: 660s