steps:
  # Decrypt env secrets
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./gcp_credentials.json.enc
      - --plaintext-file=./gcp_credentials.json
      - --location=global
      - --keyring=cloudbuild-env
      - --key=cloudbuild-env
    id: decrypt
  - name: python:3.7
    args: ["bash", "./tweets/tests/runner.sh"]
    id: pytest
  # Deploy the Docker image
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', './tweets/app.yaml', '-v', '1-scrapper-latest']
    id: deploy
timeout: 1200s