steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./env.json.enc
      - --plaintext-file=./env.json
      - --location=global
      - --keyring=cloudbuild-env
      - --key=cloudbuild-env
    id: 'decrypt key'

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tweeter-listener', './tweets/' ]
    id: 'build and deploy image to GCR'

images:
  - 'gcr.io/$PROJECT_ID/tweeter-listener'

timeout: 660s