steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./gcp_credentials.json.enc
      - --plaintext-file=./gcp_credentials.json
      - --location=global
      - --keyring=cloudbuild-env
      - --key=cloudbuild-env
    id: 'decrypt key'

  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy', './socket/app.yaml', '-v', '1-socket-latest']
    id: 'deploy app engine'

timeout: 660s